### ISSUE TITLE
Selenium logs are collected even when their reporting is disabled

### ISSUE THREAD

**Issue by HajekOndrej** [Invictum/serenity-reportportal-integration#101]
Hi, 
thanks for this great RP integration for Serenity.

I have found a little issue, that Selenium logs are collected no matter what LogUnits are enabled. They are collected even when reportportal logging is disabled with rp.enable=false.

This would normally not be a problem, but when the webdriver is Appium, Appium logs are collected for each step, which can take a lot of time and I generally don't need that.

Do you have any idea how can I disable that? 

Thanks.

**Comment by Invictum** [comment]
Hi @HajekOndrej
For now integration always tries to collect logs for UI tests, this is done for avoiding several configuration points. Seems like issue can be fixed, but it require a little rework.

**Comment by Invictum** [comment]
Implemented. Will be available in 1.5.0+
