### ISSUE TITLE
Library Verisons Updated Automatically.

### ISSUE THREAD

**Issue by sudarsunperu** [Invictum/serenity-reportportal-integration#103]
Hi @Invictum ,
I'm using the below configuration for my project. I was able to integrate to reportportal, however after Integration with this plugin, I observed that it automatically updates the Library Versions. 
e.g: In my configuration below, serenityCoreVersion is 2.0.40 but after integration it was automatically picking up 2.1.8. 

Is there a way I can use my library versions and not update it at runtime?

Thanks in advance.
```

ext{
    slf4jVersion = '1.7.7'
    serenityCoreVersion = '2.0.40'
    serenityCucumberVersion = '1.9.31'
    serenityRestAssuredVersion = '2.0.40'
    junitVersion='4.12'
    assertJVersion='3.8.0'
    logbackVersion='1.2.3'

    libs = [
            slf4jApi: "org.slf4j:slf4j-api:$slf4jVersion",
            logback: "ch.qos.logback:logback-classic:${logbackVersion}",

            test: [
                    serenity: [
                            core: "net.serenity-bdd:serenity-core:${serenityCoreVersion}",
                            junit: "net.serenity-bdd:serenity-junit:${serenityCoreVersion}",
                            cucumber: "net.serenity-bdd:serenity-cucumber:${serenityCucumberVersion}",
                            restAssured: "net.serenity-bdd:serenity-rest-assured:${serenityRestAssuredVersion}",
                    ],
                    junit: "junit:junit:${junitVersion}",
                    assertj: "org.assertj:assertj-core:${assertJVersion}"
            ]
    ]
}

```

**Comment by Invictum** [comment]
Hi @sudarsunperu 
I assume you are using gradle for dependency management and this is exactly how it resolves situation when several versions of the same lib are defined. The newest one is picked by default. You can try to use integration with older version of `serenity-core`, to achieve it try to exclude it from integration dependencies
```
    dependencies {
        compile ('com.github.invictum:serenity-reportportal-integration:1.4.3') {
                // Exclude serenity from dependencies
                exclude group: 'net.serenity-bdd'
        }
        // Define lower serenity core version
       compile: 'net.serenity-bdd:serenity-core:2.0.40'
    }
    ...
```
Potentially is may work if no major changes were made to serenity core. If no, then the only solution is to use more fresh version of serenity core.

**Comment by sudarsunperu** [comment]
Thank you @Invictum . It's picking the older version now. I'm able to see the results on Report Portal too.
