### ISSUE TITLE
Unable to integrate report portal with Serenity BDD

### ISSUE THREAD

**Issue by rbetha** [Invictum/serenity-reportportal-integration#114]
Hi,
I have integrated report portal with Serenity project(cucumber, Maven) project. I have configured reportportal.properties and 
repositories mentioned in POM.xml.  Serenity report portal integration-1.5.0.jar added as external jar as it is not available in our company. After running the test either it is not throwing any error or it is not connecting to reportportal. Need I to mentioned anything in goal while running the tests?? Could you please help on this ?

<repository>
        <snapshots>
            <enabled>false</enabled>
        </snapshots>
        <id>bintray-epam-reportportal</id>
        <name>bintray</name>
        <url>https://dl.bintray.com/epam/reportportal</url>
    </repository>

Pom Profile :

<build>
		<plugins>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-enforcer-plugin</artifactId>
				<version>1.4.1</version>
				<executions>
					<execution>
						<id>enforce</id>
						<configuration>
							<rules>
								<requireUpperBoundDeps />
								<requireJavaVersion>
									<version>1.8</version>
								</requireJavaVersion>
							</rules>
						</configuration>
						<goals>
							<goal>enforce</goal>
						</goals>
					</execution>
				</executions>
			</plugin>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>2.18</version>
				<configuration>
					<skip>true</skip>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-failsafe-plugin</artifactId>
				<version>2.19.1</version>
				<configuration>
					<includes>
						<include>**/*.java</include>
					</includes>
					<parallel>classes</parallel>
					<threadCount>5</threadCount>
					<forkCount>5</forkCount>
				</configuration>
				<executions>
					<execution>
						<goals>
							<goal>integration-test</goal>
							<goal>verify</goal>
						</goals>
					</execution>
				</executions>
			</plugin>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.2</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>

			<plugin>
				<groupId>net.serenity-bdd.maven.plugins</groupId>
				<artifactId>serenity-maven-plugin</artifactId>
				<version>${serenity.maven.version}</version>
				<dependencies>
					<dependency>
						<groupId>net.serenity-bdd</groupId>
						<artifactId>serenity-core</artifactId>
						<version>${serenity.version}</version>
					</dependency>
				</dependencies>
				<executions>
					<execution>
						<id>serenity-reports</id>
						<phase>post-integration-test</phase>
						<goals>
							<goal>aggregate</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>

**Comment by Invictum** [comment]
@rbetha 

Seems like integration wasn't enabled. If maven central isn't available, you need to download all the jars that required by integration alongside with `integration-1.5.0.jar` itself. Then you supply all the jars to the class path. The way how to do it depends of how do you run you tests.
