### ISSUE TITLE
Report Portal Rerun option Not working

### ISSUE THREAD

**Issue by bvpadmanaban** [Invictum/serenity-reportportal-integration#117]
Release used - 1.5.1 or 1.5.0
Report Portal - 5.0.0

In the below both cases, rerun not working, it is always creating new launch.

For Latest Launch Rerun
rp.rerun=true

For Specific Launch Rerun
rp.rerun=true
rp.rerun.of='launch uuid'

**Comment by Invictum** [comment]
@bvpadmanaban 

Integration doesn't support rerun option, but seems like it not hard to add it. I will consider this feature request for the next release.

**Comment by Invictum** [comment]
Implemented. Will be available in 1.5.2+
