### ISSUE TITLE
Evidence not present in RP

### ISSUE THREAD

**Issue by tmouryc** [Invictum/serenity-reportportal-integration#128]
Hi.
I would like to ask about transferring evidence into RP. I'm trying to include the reportportal integration in my project, but  the evidence stored in tests is not present in RP. Although I'm not sure whether the evidence is actually supported by your integration?

Serenity code looks like this:
`Serenity.recordReportData()
          .asEvidence()
          .withTitle("results_json.zip")
          .downloadable()
          .fromFile(FileSystems.getDefault().getPath("results_json.zip"));`

Many thanks for your reply.

**Comment by Invictum** [comment]
Hi @tmouryc 
Mentioned Serenity feature was never tested in integration. I will investigate it and share results.

**Comment by Invictum** [comment]
Implemented. Will be available in version 1.5.6
