### ISSUE TITLE
CHILD_START_TIME_EARLIER_THAN_PARENT

### ISSUE THREAD

**Issue by babantax** [Invictum/serenity-reportportal-integration#131]
Hi all!

I have spent some time debugging and finding out to see what is happening. In my case, Im executing sequentially.

This is one feature (see attached) that is causing the error. (It is a search on this page https://www.wiktionary.org/) 

Feature: Lookup a definition
  In order to talk better
  As an English student
  I want to look up word definitions

  @issue:TED-20 @example @fe
  Scenario Outline: Looking up the definition of '<word>'
    Given the user is on the Wiktionary home page
    When the user looks up the definition of the word '<word>'
    Then they should see the definition '<definition>'

    Examples:
      |word       |definition                                                                                                                          |
      |apple      |A common, round fruit produced by the tree Malus domestica, cultivated in temperate climates.                                       |
      |pear       |An edible fruit produced by the pear tree, similar to an apple but elongated towards the stem.                                      |
      |test       |A session in which a product or piece of equipment is examined under everyday or extreme conditions to evaluate its durability, etc.|
      |software   |(computing) Encoded computer instructions, usually modifiable (unless stored in some form of unalterable memory such as ROM).       |
The issue only happens when the feature has a DataTable and the process is done by BddDataDriven instead of Regular.
The first example(apple) is executed properly. One test with 3 children (3 steps)
![image](https://user-images.githubusercontent.com/52815118/104018074-8493a400-51b9-11eb-966f-9eb151127ab4.png)

With the second the problem begins. TestOut comes with the steps of apple and pear and the proceedSteps method try to log all of them to the actual Test(pear):
![image](https://user-images.githubusercontent.com/52815118/104018105-9412ed00-51b9-11eb-94bb-76ff504cdb2b.png)

With the following examples is the same "test" try to process the steps of apple and pear.

The log output error is because is trying to log old steps in a new test:
![image](https://user-images.githubusercontent.com/52815118/104018128-9e34eb80-51b9-11eb-8ddc-15236bfe3c95.png)

Apparently the report in reporting portal is fine because that older steps are not logged but console log is totally full of them. 

In my case, the problem seems fixed modifying BddDataDriven(record method) by passing only the steps of the current test (see below) but I don´t know if this can cause problems on other kinds of features/tests....
![image](https://user-images.githubusercontent.com/52815118/104018220-bf95d780-51b9-11eb-8270-7940370e8fba.png)

**Comment by zzoubian** [comment]
I also noticed a similar issue

**Comment by Invictum** [comment]
Fixed. Will be available in 1.5.6
