### ISSUE TITLE
Not all of tests are shown in reportportal after upgrade to latest serenity-reportportal-integration

### ISSUE THREAD

**Issue by marek2209** [Invictum/serenity-reportportal-integration#133]
We trying to run tests via mvn task on azure devops and on new version of plugin but only part of tests is getting triggered. Instead of 22 as always only half of it is getting triggered. Probably something is wrong with -Dtags parameter.
Our mvn task looks like:

 task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
  `    goals: 'clean verify -Dwebdriver.remote.url=http://ip_of_grid:80/wd/hub -Dwebdriver.remote.driver=chrome -Denvironment=someEnv -Dchannel=someData -Dtags=b2b,sanity -Drp.launch="someLaunchNAme"'`

we also tried with options:
-Dcucumber.options="--tags @b2b --tags @P1"

-Dcucumber.filter.tags="@b2b and @P1"

Everything worked  as expected on 1.4.3 version and even locally. Only maven on azure devops agent provides such errors.....

**Comment by Invictum** [comment]
Hi,

Integration itself doesn’t alter native Serenity’s mechanism for tests execution based on tag filter.
Do you get the same results without integration?
If so it is better to ask in serenity github at https://github.com/serenity-bdd

**Comment by marek2209** [comment]
without integration and with old 1.4.3 version I get different results - proper number of tests are executed

**Comment by Invictum** [comment]
@marek2209

Integration version `1.4.3` and `1.5.5` uses different Serenity cores.
May I ask you to check how tags based execution works without integration in dependencies for two different Serenity versions: `2.1.8` and `2.3.4`?

**Comment by grey-rain** [comment]
Closed due to inactivity.
More likely, Serenity core issue.
