### ISSUE TITLE
ReportPortal returned errors CHILD_START_TIME_EARLIER_THAN_PARENT during parallel testrun

### ISSUE THREAD

**Issue by dileytes** [Invictum/serenity-reportportal-integration#143]
I have a same issue in my project as https://github.com/Invictum/serenity-reportportal-integration/issues/78
I wrote synthetic test for reproduce this issue https://github.com/dileytes/reportportal-issue, but it cannot 100% reproduce the issue. Sometimes it takes two to three runs before the problem appears

**Comment by grey-rain** [comment]
abandoned.
