### ISSUE TITLE
 Incorrect Request. [Field 'attributes[].value' should have size from '1' to '128'.] 

### ISSUE THREAD

**Issue by plokeshwar** [Invictum/serenity-reportportal-integration#145]
Suddenly, I started getting this error.  Any help would be greatly appreciated.

19:30:16.058 [rp-io-63] ERROR c.e.r.utils.SubscriptionUtils - [109] ReportPortal Finish test item execution error
com.epam.reportportal.exception.ReportPortalException: Report Portal returned error
Status code: 400
Status message: 
Error Message: Incorrect Request. [Field 'attributes[].value' should have size from '1' to '128'.] 
Error Type: INCORRECT_REQUEST

        at com.epam.reportportal.service.ReportPortalErrorHandler.handleError(ReportPortalErrorHandler.java:85) ~[client-java-5.0.11.jar:na]
        at com.epam.reportportal.service.ReportPortalErrorHandler.handle(ReportPortalErrorHandler.java:61) ~[client-java-5.0.11.jar:na]
        at com.epam.reportportal.restendpoint.http.HttpClientRestEndpoint$1.subscribe(HttpClientRestEndpoint.java:526) ~[client-java-5.0.11.jar:na]
        at io.reactivex.i

**Comment by bvpadmanaban** [comment]
what value are you passing in rp.attributes in report portal properties file?

**Comment by v1-wizard** [comment]
You should go to your Report Portal instance and read logs from API-gateway and find requests with data that produce this error. Look like you start sending data with the size of more than 128 chars in attributes. This is not a problem with Report Portal or serenity-reportportal-integration. This is a sudden limitation and you should fix your data on tests execution.

**Comment by v1-wizard** [comment]
You could also try this option in your code:
`ReportIntegrationConfig.get().truncateNames(true)`

**Comment by plokeshwar** [comment]
> what value are you passing in rp.attributes in report portal properties file?

I am not passing any attributes from reportportal.properties.

**Comment by plokeshwar** [comment]
> You could also try this option in your code: `ReportIntegrationConfig.get().truncateNames(true)`

Let me try this.

**Comment by plokeshwar** [comment]
@Invictum this looks to be occurring for Scenario Outlines with long scenario descriptions.

**Comment by grey-rain** [comment]
@plokeshwar I know it is been a while, but I cannot replicate the issue with the latest version 1.6.0.
More likely it was ReportPortal limitation which is lifted now...

**Comment by grey-rain** [comment]
abandoned.
