### ISSUE TITLE
java.lang.NullPointerException at com.github.invictum.reportportal.SuiteStorage.lambda

### ISSUE THREAD

**Issue by plokeshwar** [Invictum/serenity-reportportal-integration#146]
@Invictum When the tests pass, there is no issue. But when one of the example test fails, the entire execution is stopped and the below error is thrown and the report is not published. Also, there is no GivenStories tag being used. Any help would be greatly appreciated.  If I remove the dependency from POM, then the test continues as expected.  Very weird.

Below are the versions and report portal dependency
<serenity.version>2.3.11</serenity.version>
<serenity.rest.version>2.3.11</serenity.rest.version>
<serenity.maven.version>2.4.1</serenity.maven.version>
<serenity.cucumber.version>2.3.2</serenity.cucumber.version>

        <artifactId>serenity-reportportal-integration</artifactId>
        <version>1.5.8</version>
11:54:29.827 [pool-2-thread-1] DEBUG n.s.core.photography.Darkroom - Closing darkroom
null
java.lang.NullPointerException
at com.github.invictum.reportportal.SuiteStorage.lambda$finalizeActive$2(SuiteStorage.java:57)
at
java.base/java.util.concurrent.ConcurrentHashMap$ForEachKeyTask.compute(ConcurrentHashMap.java:4992)
at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)

**Comment by plokeshwar** [comment]
@Invictum Any suggestion?

**Comment by grey-rain** [comment]
@plokeshwar I know it is been a while, but I am reviewing some old issues.
Unfortunately, `GivenStories` tag is currently not supported. (same as https://github.com/Invictum/serenity-reportportal-integration/issues/87).
As for the issue when execution stopped when Failed test is met, could you please provide more details on your test structure? I cannot replicate it locally in a simple case.
Thanks!

**Comment by grey-rain** [comment]
abandoned.
