### ISSUE TITLE
Auto generate skip testcase

### ISSUE THREAD

**Issue by huongkhuongit** [Invictum/serenity-reportportal-integration#150]
![image](https://user-images.githubusercontent.com/82049341/191242621-9018b246-5b57-42c6-b8d2-650b42c1b3e8.png)
Hi everyone, I got a problem. When I got a fail testcase, reportportal allways generate a skip testcase. So how can I fix it?

**Comment by huongkhuongit** [comment]
I using:
        <dependency>
            <groupId>com.github.invictum</groupId>
            <artifactId>serenity-reportportal-integration</artifactId>
            <version>1.5.7</version>
        </dependency>
        <serenity.version>3.0.5</serenity.version>
        <serenity.maven.version>3.0.5</serenity.maven.version>
        <serenity.cucumber.version>3.0.5</serenity.cucumber.version>

**Comment by grey-rain** [comment]
@huongkhuongit I know, it's been a while, but currently I cannot reproduce it. It would be great if you could provide example of your test case, otherwise it is impossible to debug.
Thanks!

**Comment by grey-rain** [comment]
abandoned.
