### ISSUE TITLE
How to convert error test case in serenity to failure test case in rp?

### ISSUE THREAD

**Issue by huongkhuongit** [Invictum/serenity-reportportal-integration#151]
**How to convert error test case in serenity to failure test case in rp?**
So error testcase will become skip testcase in rp. I can't see any step in skip testcase.
**How can I see step in skip test case or some thing like that?**
![image](https://user-images.githubusercontent.com/82049341/191658306-4e77ade9-17a4-4c02-b4b6-324917dbab2a.png)

**Comment by grey-rain** [comment]
@huongkhuongit I know it's been a while, but it would be great if you could provide example of your test and exception thrown. It is not really clear what do you mean by "error test case" and how to replicate it.

**Comment by grey-rain** [comment]
abandoned.
