### ISSUE TITLE
Implementing support for parallel execution

### ISSUE THREAD

**Issue by babantax** [Invictum/serenity-reportportal-integration#155]
I' m very happy with this integration, I think is working very fine.

But it looks like it's been maintained for a while now. Only thing I miss is support for parallel executions, I think is quite complex.

Is there any plan to work in that in the future?

Thanks a lot :)

**Comment by grey-rain** [comment]
@babantax Thanks for the kind words!
Yes, there are plans to enable parallel execution. It is definitely on the roadmap and actually is one of the main features on it. Stay tuned for more updates :)
