### ISSUE TITLE
Random error with async reporting

### ISSUE THREAD

**Issue by babantax** [Invictum/serenity-reportportal-integration#175]
Hello!

Just testing **release 1.6.0** and If I use async reporting **rp.reporting.async = true**, half of the launches more or less are lost.

With  **rp.reporting.async = false** is working fine. Not sure if this bug is related to this repository or is on the client-java 5.1.22 dependency, [see more info here](https://github.com/reportportal/client-java/issues/222).

Thank a lot in advance

**Comment by grey-rain** [comment]
@babantax hello! I am not sure where this issue should reside... never happened to me. lets try investigating it together! :)
are results missed only in ReportPortal, e.g do you still see native Serenity report for those executions?

P.S. I found this issue related to async reporting https://github.com/Invictum/serenity-reportportal-integration/issues/118 . It seems like (prety long time ago) it behaved differently for async reporting from what you describe.

**Comment by grey-rain** [comment]
abandoned.
