### ISSUE TITLE
Providing properties through Java class rather than .properties file

### ISSUE THREAD

**Issue by asif-choudhari** [Invictum/serenity-reportportal-integration#179]
Hi, 
I would like to know if there is a functionality to set properties like baseUrl, apiKey and others through Java implmentation, rather than .properties file.
Can such feature be implemented if not present.

**Comment by grey-rain** [comment]
hi @asif-choudhari ! it is not a requirement of current integration, but a requirement of ReportPortal itself. So if you would like to be sure in the answer, you'd better address this question to ReportPortal guys.
Best regards!
