### ISSUE TITLE
Record data with Serenity.recordReportData().withTitle().andContents();

### ISSUE THREAD

**Issue by sumanguduru** [Invictum/serenity-reportportal-integration#180]
I'm seeking assistance with recording data into ReportPortal. I've been attempting to use the following steps to record some data into a report, but it doesn't seem to be transferring to ReportPortal:

`Serenity.recordReportData()
        .withTitle("Request Decrypted")
        .andContents(decryptedRequest);
`

I am using version: 1.6.0
serenity version:  4.1.0

**Comment by grey-rain** [comment]
hi @sumanguduru !
it seems like you're trying to log data in a wrong way. Usually common logger is used without a need to call to static Serenity classes.
I found the following on ReportPortal website:
https://github.com/reportportal/client-java/wiki/Nested-steps

I hope it helps.

**Comment by grey-rain** [comment]
Closed, as it is abandoned.
