### ISSUE TITLE
"Latest Launches" Option in Widget Displays Same Data as "All launches"

### ISSUE THREAD

**Issue by Priyanshu19992002** [Invictum/serenity-reportportal-integration#184]
# Description:
The option of **Latest Launches** in various widgets like **Overall Statistics**, **Component Health Check**, **Component Health Check (Table view)**, **Launches Duration Chart** etc. is expected to show data specifically for the most recent launches. However, I have noticed that it is displaying the same information as the **All Launches** option in the widget, making it difficult to distinguish between the two. When it was compared with another RP agent ```agent-java-karate``` the same functionality works as per the expectation that is data is getting segregated for **All Launches** and **Latest Launches** configuration on the widgets so it seems as if the agent ```serenity-reportportal-integration``` is having some bug.

# Steps to Reproduce:
- Integrate the Serenity Framework with serenity-reportportal-integration agent v1.5.7
- Ingest multiple launches into ReportPortal.
- Create a Dashboard and filter for these launches to be displayed in ReportPortal
- Go to the dashboard in ReportPortal.
- Add a widget that can display data for both **All Launches** and **Latest Launches**.
- Configure the widget to show data for **Latest Launches**.
- Add the same widget above but now configure the widget to show data for **All Launches**.
- Observe the data displayed in the widget for both **All Launches** and **Latest Launches**.

# Expected Behaviour
- The **Latest Launches** configured widget should show data only for the most recent launches, distinct from the **All Launches** widget.

# Actual Behaviour
- The **Latest Launches** widget is displaying the same data as the **All Launches** widget.

# Screenshot
Below screenshot (for RP v24.1) is for widget **Overall Statistics** but the behaviour is observed in all the widgets (which can be configured to show latest launches)

- This shows two launches ingested in RP
<img width="1381" alt="Screenshot 2024-08-20 at 5 43 59 PM" src="https://github.com/user-attachments/assets/97ffbb7a-d09d-436a-8d00-31b62defc071">

- This shows "Overall Statistics" widget with comparision of **All Launches** and **Latest Launches** showing same number but it should show for **All Launches** = 2 Test and for **Latest Launches** = 1 Test.
<img width="1370" alt="Screenshot 2024-08-20 at 6 20 21 PM" src="https://github.com/user-attachments/assets/51385293-d8bc-4087-a865-e38490ae8f71">

- This is the filter used in the above widget.
<img width="1370" alt="Screenshot 2024-08-20 at 5 47 23 PM" src="https://github.com/user-attachments/assets/41af0ea2-6799-424c-a846-ad672de89e9b">

# Environment
Tested for two environment as below:
```
- ReportPortal Version: v24.1
- Browser: Chrome v127.0.6533.120
- RP Agent: serenity-reportportal-integration v1.5.7
- OS: macOs Sonoma 14.2.1
```

```
- ReportPortal Version: API Service: 5.10.1;Index Service: 5.10.0;Jobs Service: 5.10.0;Authorization Service: 5.10.0;Service UI: 5.10.0;
- Browser: Chrome v127.0.6533.120
- RP Agent: serenity-reportportal-integration v1.5.7
- OS: RHEL 8
```

**Comment by grey-rain** [comment]
hello @Priyanshu19992002 !
What you're showing is ReportPortal issue, it has nothing to do with Serenity integration.
Please address it to ReportPortal developers.
Thank you!

**Comment by Priyanshu19992002** [comment]
Hi @grey-rain ,

Thanks for replying. I will close this ticket and will check with ReportPortal developers. If required then will open the ticket again.
