### ISSUE TITLE
Support of @RunWith(CucumberWithSerenity.class)

### ISSUE THREAD

**Issue by nstbushneva** [Invictum/serenity-reportportal-integration#48]
Hi,

I use serenity integration with cucumber. I found that the official cucumber plugin doesn't work for me as it works with old version cucumber while all latest serenity integrations are based on latest cucumber (> 2.x).

Is this plugin to support @RunWith(CucumberWithSerenity.class) in addition to just @RunWith(Serenity.class) ? 

As now there are official cucumber plugin and this one for serenity but seems there is now plugin which can handle integration of those two. If I try to use this one with @RunWith(CucumberWithSerenity.class) then for some reason, it tried to initialize webdriver while there is no use of webdriver in the whole project. 

If I don't use the plugin in pom then the test works fine. Otherwise, it gives: 
'''
TEST STARTED: Basic scenario
-------------------------------------------------------------------(basic-feature-file-that-used-in-order-to-test-an-integration-with-report-portal;basic-scenario)
Feature: Basic feature file that used in order to test an integration with Report Portal

  @VerifyCucumber @API
  Scenario: Basic scenario                                      # src/test/resources/basic_cucumber_test.feature:4
Nov 13, 2018 11:16:23 PM org.openqa.selenium.remote.DesiredCapabilities firefox
INFO: Using `new FirefoxOptions()` is preferred to `DesiredCapabilities.firefox()`
Nov 13, 2018 11:16:23 PM org.openqa.selenium.remote.DesiredCapabilities firefox
INFO: Using `new FirefoxOptions()` is preferred to `DesiredCapabilities.firefox()`

'''

**Comment by Invictum** [comment]
Hi @nstbushneva 

`serenity-reportportal-integration` module build around `serenity-core`. So it should work with all Serenity test automation frameworks that use that core - including `serenity-cucumber`, that I assume you are using.

Serenity-cucumber [manual]() describes only one way of integration with Cucumber - with `@RunWith(CucumberWithSerenity.class)` runner class. So I am not sure `@RunWith(Serenity.class)` will work at all.

As for strange web driver init in non UI tests - it is an issue in `serenity-reportportal-integration` module. So thanks for highlighting this problem.

**Comment by Invictum** [comment]
@nstbushneva 

Sure! Thanks for willing to help, I'm really appreciate it.
I am going to close current issue and let you know when fix of #49 will be ready.
