### ISSUE TITLE
"Error Type: FINISH_LAUNCH_NOT_ALLOWED" on running CucumberWithSerenity.class

### ISSUE THREAD

**Issue by nstbushneva** [Invictum/serenity-reportportal-integration#53]
I have created a dummy test project that contains Serenity and CucumberWithSerenity tests in order to verify their integration with Report Portal.
This project configured with:

- serenity-reportportal-integration [1.3.0-SNAPSHOT]
- maven-failsafe-plugin [2.19.1]
- serenity-core [1.9.45]
- serenity-cucumber [1.9.8]

The project contains cucumber tests that have a common step.
When I'm trying to execute only one of these tests with its specific tag, I am getting the following error:

>  [rp-io-7] ERROR com.epam.reportportal.service.Launch - [38] ReportPortal execution error
> com.epam.reportportal.exception.ReportPortalException: Report Portal returned error
> Status code: 406
> Status message: Not Acceptable
> Error Message: Finish launch is not allowed. Launch '5bf2acdd756b5f0001dfd448' has items '[5bf2acdf756b5f0001dfd44e]' with 'IN_PROGRESS' status
> Error Type: FINISH_LAUNCH_NOT_ALLOWED
> 
>         at com.epam.reportportal.service.ReportPortalErrorHandler.handleError(ReportPortalErrorHandler.java:83)
>         at com.epam.reportportal.service.ReportPortalErrorHandler.handle(ReportPortalErrorHandler.java:59)
>         at com.epam.reportportal.restendpoint.http.HttpClientRestEndpoint$1.subscribe(HttpClientRestEndpoint.java:517)
>         at io.reactivex.internal.operators.maybe.MaybeCreate.subscribeActual(MaybeCreate.java:45)
>         at io.reactivex.Maybe.subscribe(Maybe.java:4096)
>         at io.reactivex.internal.operators.maybe.MaybeCache.subscribeActual(MaybeCache.java:77)
>         at io.reactivex.Maybe.subscribe(Maybe.java:4096)
>         at io.reactivex.internal.operators.maybe.MaybeSubscribeOn$SubscribeTask.run(MaybeSubscribeOn.java:54)
>         at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
>         at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>         at java.lang.Thread.run(Thread.java:748)

It happens only when I run a specific test that uses steps utilized by other scenarios. It seems that Report Portal is trying to fetch the results of tests that should be skipped and getting stuck. 

I've attached a simple project that reproduces the issue: 
[simple-test-framework-with-serenity-and-cucumber_2.zip](https://github.com/Invictum/serenity-reportportal-integration/files/2595251/simple-test-framework-with-serenity-and-cucumber_2.zip)

The command that executes only one of this tests: 
 `mvn clean verify -fae -Dcucumber.options="--tags @VerifyCucumber2" `

**Comment by Invictum** [comment]
@nstbushneva 
Looks it is related to an old Serenity issue https://github.com/serenity-bdd/serenity-core/issues/707
I will try to find a workaround for it from integration side, but this will be really tricky.

**Comment by nstbushneva** [comment]
Hi @Invictum, 
Thank you for the update! I look forward to hearing from you)

**Comment by Invictum** [comment]
@nstbushneva 
Solution was found, I will create a PR with fix.

**Comment by Invictum** [comment]
@nstbushneva 
Fix is available in `1.3.0-SNAPSHOT` version

**Comment by Invictum** [comment]
Fixed. Will be available in version 1.3.0

**Comment by nstbushneva** [comment]
Hi @Invictum, 
Thanks a tone for the new release! Everything is working perfectly fine!

**Comment by Invictum** [comment]
@nstbushneva 
You are welcome. Thank you for issues reporting!
