### ISSUE TITLE
Rest Assured reports integration 

### ISSUE THREAD

**Issue by nstbushneva** [Invictum/serenity-reportportal-integration#64]
*Hi @Invictum, I'd like to thank you for all the efforts you have put in the serenity-reportportal-integration project. 
You have made our life much easier by providing such listener, as now we can represent all our test results in the Report Portal on a daily basis.*

*I created this issue just to suggest a minor thing for the further improvement of the serenity-reportportal-integration project.* 

Serenity + Rest Assured is a widely used combination for API verification which provides outstanding test reports out-of-the-box. 
Currently, RP doesn't have a feature to reflect request/response data in the test results: 
![rest-assured-reporting](https://user-images.githubusercontent.com/36731862/54124946-64073100-440c-11e9-86d3-c5f84d15bae2.gif)
Would it be feasible to add the additional information for rest-assured-based tests to Report Portal along with interactive dashboard capabilities? I hope, it will be a piece of cake for you to make it real.
It would be really beneficial for users of the serenity-reportportal integrator. Thank you! 

In order to check the current reporting, please execute API tests from [simple-multimodule-project.zip](https://github.com/Invictum/serenity-reportportal-integration/files/2951876/simple-multimodule-project.zip)
```bash
 mvn clean verify -Dcucumber.options="--tags '@API'"
```

**Comment by Invictum** [comment]
@nstbushneva 
Yes, it is possible. I will schedule this functionality to add in `1.4.0` version.
In case if you need functionality ASAP, it is possible to create custom [log unit](https://github.com/Invictum/serenity-reportportal-integration#log-units). Rest request and response info is accessible via `TestStep.hasRestQuery` and `TestStep.getRestQuery` methods.

**Comment by nstbushneva** [comment]
@Invictum, thank you for getting back to me! 
This is a nice-to-have feature. Thus, there is no hurry.

**Comment by Invictum** [comment]
Implemented. Will be available in version 1.4.0+
