### ISSUE TITLE
Turn off integration without removing from project

### ISSUE THREAD

**Issue by theguywhodoesthething** [Invictum/serenity-reportportal-integration#81]
Is there a way to turn off reportportal for a test launch without removing it from my project completely? I'd like to have two tasks in my build.gradle, one that logs to reportportal, and one that doesn't. Is this possible?

**Comment by Invictum** [comment]
@theguywhodoesthething 

Sure, you can easily control RP client with `rp.enable` option. Just pass it as JVM argument:
```
gradle test -Drp.enable=false
```
Other option could be set it to system properties with some gradle plugin, but exact usage depends on plugin itself.

For more details about RP configuration please refer to [RP documentation](https://reportportal.io/docs/JVM-based-clients-configuration).

**Comment by Invictum** [comment]
@theguywhodoesthething 
I am going to close this issue. Feel free to open a new one in case of extra questions.
