### ISSUE TITLE
How to align features to items in Report Portal

### ISSUE THREAD

**Issue by theguywhodoesthething** [Invictum/serenity-reportportal-integration#85]
Is there a way to configure the integration to add separate features as items under a launch? Right now the default behavior is that the all scenarios are added as tests under one feature that is seemingly selected at random. I believe it might be due to how we are setting up our test runner, which is in a separate TestSupport class.
```
@RunWith(CucumberWithSerenity.class)
@CucumberOptions(
    features = "src/test/resources/features",
    glue = "com.serenity.autotest.project")
public class TestSupport {}
```
Please let me know if this is possible with the existing module. Thanks.

**Comment by Invictum** [comment]
Hi @theguywhodoesthething and thanks for question

In accordance to your runner all features from `src/test/resources/feature` directory will be scheduled for execution.
Integration will threat each feature file as separate suite that may have several children (scenarios).

If you will have several runners that contains intersected feature files, then corresponding tests will be executed twice as well as logged twice to the Report Portal server.

`Feature` section should be defined in feature file to make this work

```
Feature: Feature Name
  Some feature description

  Scenario: Scenario 1
    Given there is a dummy condition that must be fulfilled
    Then the dummy expected result should be verified

  Scenario: Scenario 2
    Given there is a dummy condition that must be fulfilled
    Then the dummy expected result should be verified
```

**Comment by Invictum** [comment]
@theguywhodoesthething 
Issue is closed due to inactivity
